export enum Category {
  Biographies = 'biographies',
  Collections = 'collections',
  Behavior = 'behavior',
  Tales = 'tales',
  LiteraryCriticism = 'literary-criticism',
  ScienceFiction = 'scienceFiction',
  Folklore = 'folklore',
  Humor = 'humor',
  Children = 'children',
  Games = 'games',
  Newspapers = 'genealogy',
  BrazilianLiterature = 'brazilian-literature',
  ForeignLiterature = 'foreign-literature',
  RareBooks = 'rare-books',
  Poetry = 'poetry',
  AnotherSubjects = 'another-subjects',
}
